### ISSUE TITLE
Bug in Roll Convention MODIFIED_FOLLOWING_EOM

### ISSUE THREAD

**Issue by FuggeWolf** [frontmark/jupyter-notebooks#18]
Sometimes the roll convention doesn't derive the correct end date:

- start date 29-Apr-2022 (Friday), period 1 month, end date: 31-May-2022 (Tuesday).
  30-Apr-2022 is a Saturday, so 29-Apr-2022 is the last business day of the month.
  Unexpected result: 30.05.2022
- start date 28-Feb-2020 (Friday), period 1 month, end date: 31-Mar-2020 (Tuesday).
  Though 2020 is a leap year, the 28-Feb-2020 is the last business day of the month.
  Unexpected result: 30.03.2020

**Comment by favdo** [comment]
diese Konvention kann nun nicht mehr ausgewählt werden, da sie entfernt wurde
